### ISSUE TITLE
跨行 Cloze 问题

### ISSUE THREAD

**Issue by pilgrimlyieu** [pilgrimlyieu/Anki#2]

**Comment by pilgrimlyieu** [comment]
这是渲染机制引起的，可以说是基本无法修复，即使修复可能也会破坏代码块的渲染（通过调换渲染和替换的顺序）。

**Comment by pilgrimlyieu** [comment]
可以用下面的 CSS 隐藏这个引发的空段落问题：

```css
p:has(> span.cloze:empty:only-child) {
  display: none;
}
```
